apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkZWVwYW5zaHUxNDExIiwicGFzc3dvcmQiOiJkZWVwYW5zaHU4IiwiZW1haWwiOiJkZWVwYW5zaHVzdXBlcjE2QGdtYWlsLmNvbSIsImF1dGgiOiJaR1ZsY0dGdWMyaDFNVFF4TVRwa1pXVndZVzV6YUhVNCJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2021-09-15T11:27:36Z"
  name: docker-secrets
  namespace: default
  resourceVersion: "7416586"
  uid: b8af92b7-079e-49bb-b12f-cd4a8c6845f0
type: kubernetes.io/dockerconfigjson
